apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0db9fbcc0e9f4b24d
    volumeAttributes:
      dnsname: fs-0db9fbcc0e9f4b24d.fsx.us-west-2.amazonaws.com
      mountname: hqzdbb4v
