apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: adot-obo-trace-tempo-instrumentation
  namespace: app
spec:
  exporter:
    endpoint: http://adot-obo-trace-tempo-collector.adot-collector.svc.cluster.local:4318
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    # temp
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.51b0
    env:
    - name: OTEL_METRICS_EXPORTER
      value: none
