---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: adot-collector
  name: adot-obo-trace-tempo

---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: adot-collector
  name: adot-obo-trace-tempo
spec:
  mode: deployment
  replicas: 1
  serviceAccount: adot-obo-trace-tempo
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi

  env:
  - name: CLUSTER_NAME
    value: eks-adot-ob-eks

  config: |
    extensions:
      health_check:

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
        
    exporters:
      otlphttp:
        endpoint: http://tempo.observability:4318
        tls:
          insecure: true
        
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      resource:
        attributes:
        - key: k8s.cluster.name
          value: $CLUSTER_NAME
          action: insert
        
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces, resource]
          exporters: [otlphttp]
