apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: "100"
  template:
    metadata:
      labels:
        team: checkout
        env: dev
    spec:
      nodeClassRef:
        name: default
      taints:
        - key: "dedicated"
          value: "CheckoutApp"
          effect: "NoSchedule"
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values: ["c5", "m5", "m6i", "m6a", "r4", "c4"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand", "spot"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]