apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks
  region: ap-northeast-2
  version: "1.25"  

vpc:
  id: vpc-05a960a0837da1328
  cidr: 192.168.0.0/16
  securityGroup: sg-0c59ddf1a9a73edc9
  nat:
    gateway: HighlyAvailable

  subnets:
    public: 
      public-2a:
        id: subnet-06391e7ab56a8ae9c
        cidr: 192.168.1.0/24
      public-2c:
        id: subnet-00c193bd6e515a79b
        cidr: 192.168.2.0/24
    private:
      private-2a:
        id: subnet-02d592518f7ae0755
        cidr: 192.168.3.0/24
      private-2c:
        id: subnet-0dcfc3b165e7b355d
        cidr: 192.168.4.0/24

  clusterEndpoints:
    publicAccess: false 
    privateAccess: true 

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 3
    privateNetworking: true 
    ssh:
      publicKeyName: eks-terraform-key
    availabilityZones:
      - ap-northeast-2a
      - ap-northeast-2c
    iam:
      withAddonPolicies:
        imageBuilder: true 
        albIngress: true  
        cloudWatch: true 
        autoScaler: true 
    instanceName: EKS-WORKER-TEST
    volumeSize: 30
